# Generated by Django 3.0.5 on 2020-05-24 00:39

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Veuillez entrer votre numero de telephone.', max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(choices=[('1', 'Eastern Cape'), ('2', 'Free State'), ('3', 'Gauteng'), ('4', 'KwaZulu-Natal'), ('5', 'Limpopo'), ('6', 'Mpumalanga'), ('7', 'Nothern Cape'), ('8', 'North West'), ('9', 'Western Cape')], default=1, max_length=15)),
                ('zip_code', models.IntegerField()),
                ('institution', models.CharField(max_length=10)),
                ('visa_expiry_date', models.DateField(verbose_name='expiry date')),
            ],
        ),
    ]
