# Generated by Django 3.0.5 on 2020-05-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='visa_expiry_date',
            field=models.DateField(verbose_name='expiry date'),
        ),
    ]
